### ISSUE TITLE
bug: Modern Fortran extension not working despite specifying fortls path

### ISSUE THREAD

**Issue by AgilentGCMS** [fortran-lang/vscode-fortran-support#1060]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have tried the Pre-Release of the extension.

- [X] I have replicated the Issue in the latest Pre-Release

### Description

I have installed the "Modern Fortran" extension and specified the path to fortls in settings:

![Screenshot 2024-02-22 at 10 27 30 AM](https://github.com/fortran-lang/vscode-fortran-support/assets/3866945/d0731766-4b6e-4ecd-9337-c38e173328f8)

```
$ ls -l /Users/sbasu1/Library/Python/3.11/bin/fortls
-rwxr-xr-x 1 sbasu1 staff 294 2023 Jul 31 14:09:12 /Users/sbasu1/Library/Python/3.11/bin/fortls
```

However, when I open a `F90` file in Visual Studio Code, I get the following error:

```
Traceback (most recent call last):
  File "/Users/sbasu1/Library/Python/3.11/lib/python/site-packages/fortls/langserver.py", line 167, in handle
    resp = handler(request)
           ^^^^^^^^^^^^^^^^
  File "/Users/sbasu1/Library/Python/3.11/lib/python/site-packages/fortls/langserver.py", line 195, in serve_initialize
    self._resolve_globs_in_paths()
  File "/Users/sbasu1/Library/Python/3.11/lib/python/site-packages/fortls/langserver.py", line 1620, in _resolve_globs_in_paths
    source_dirs.update(set(only_dirs(resolve_globs(path, self.root_path))))
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sbasu1/Library/Python/3.11/lib/python/site-packages/fortls/helper_functions.py", line 337, in resolve_globs
    return [str(p.resolve()) for p in Path(root).glob(rel)]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sbasu1/Library/Python/3.11/lib/python/site-packages/fortls/helper_functions.py", line 337, in <listcomp>
    return [str(p.resolve()) for p in Path(root).glob(rel)]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sbasu1/packages/macports/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pathlib.py", line 952, in glob
    selector = _make_selector(tuple(pattern_parts), self._flavour)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sbasu1/packages/macports/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pathlib.py", line 282, in _make_selector
    pat = pattern_parts[0]
          ~~~~~~~~~~~~~^^^
IndexError: tuple index out of range
```

### Expected Behaviour

I expect the modern fortran extension to work without problems.

### Version of Modern Fortran

v3.2.0

### Version of Visual Studio Code

1.74.0

### Platform and Architecture

MacOS

**Comment by gnikit** [comment]
This is not a bug report, please do not open issues for support. You have also ignored the mandatory checks i.e. not installed the pre-release or searched for similar issues, they are not there for cosmetic reasons, they serve a purpose!

The error you are receiving states that fortls works fine and it crashes resolving source directories, which in your case are very likely user supplied. You have omitted any and all information to make this issue reproducible. Before seeking support you should attempt to troubleshoot the problem yourself, and importantly reading the documentation of fortls (https://fortls.fortran-lang.org/) should be the first step.

This issue will be converted to a Discussion but for future support use Fortran-lang Discourse.
