### ISSUE TITLE
[BUG] Install error under Remote Development

### ISSUE THREAD

**Issue by baip** [fortran-lang/vscode-fortran-support#521]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'm trying to install the Modern Fortran extension for Remote Development. The installation failed with WSL (v1) or an SSH server, both running Ubuntu 20.04.4 LTS, giving the following error. The extension was successfully installed in the `~/.vscode-server/extensions` folder on the server side, but the error message seems to indicate that the extension wanted to rename something on the client side `%appdata%\.vscode`, which doesn't have this extension.

WSL:
~~~
[2022-06-08 13:02:53.637] [renderer1] [info] Invoking resolveAuthority(wsl)
[2022-06-08 13:02:55.463] [renderer1] [info] resolveAuthority(wsl) returned '127.0.0.1:65073' after 1826 ms
[2022-06-08 13:03:03.009] [renderer1] [warning] No search provider registered for scheme: vscode-remote, waiting
[2022-06-08 14:32:17.140] [renderer1] [info] Not activating extension 'ms-vscode.cpptools': Timed out while searching for 'workspaceContains' pattern /.vscode/c_cpp_properties.json
[2022-06-08 14:34:03.877] [renderer1] [error] ["EPERM: EPERM: operation not permitted, rename 'c:\\Users\\USER\\.vscode\\extensions\\.98dd4840-8e8d-4e08-885f-ed1c9ab7c760' -> 'c:\\Users\\USER\\.vscode\\extensions\\ms-vscode.cpptools-1.9.8-win32-x64'","    at F.rename (vscode-file://vscode-app/c:/Users/USER/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:213259)","    at async F.extractUserExtension (vscode-file://vscode-app/c:/Users/USER/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:210508)","    at async q.extract (vscode-file://vscode-app/c:/Users/USER/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:217008)","    at async q.doRun (vscode-file://vscode-app/c:/Users/USER/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:217949)"]
[2022-06-08 14:34:03.932] [renderer1] [error] EPERM: operation not permitted, rename 'c:\Users\USER\.vscode\extensions\.98dd4840-8e8d-4e08-885f-ed1c9ab7c760' -> 'c:\Users\USER\.vscode\extensions\ms-vscode.cpptools-1.9.8-win32-x64': EPERM: EPERM: operation not permitted, rename 'c:\Users\USER\.vscode\extensions\.98dd4840-8e8d-4e08-885f-ed1c9ab7c760' -> 'c:\Users\USER\.vscode\extensions\ms-vscode.cpptools-1.9.8-win32-x64'
    at F.rename (vscode-file://vscode-app/c:/Users/USER/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:213259)
    at async F.extractUserExtension (vscode-file://vscode-app/c:/Users/USER/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:210508)
    at async q.extract (vscode-file://vscode-app/c:/Users/USER/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:217008)
    at async q.doRun (vscode-file://vscode-app/c:/Users/USER/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:217949)
~~~

Linux SSH server:
~~~
[2022-06-08 14:37:53.940] [renderer3] [info] Invoking resolveAuthority(ssh-remote)
[2022-06-08 14:37:56.096] [renderer3] [error] [Extension Host] (node:23884) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
[2022-06-08 14:37:56.110] [renderer3] [info] resolveAuthority(ssh-remote) returned '127.0.0.1:65316' after 2170 ms
[2022-06-08 14:37:57.953] [renderer3] [error] Could not find pty on pty host: Error: Could not find pty on pty host
    at m._throwIfNoPty (/home/USER/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:20:5333)
    at m.updateTitle (/home/USER/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:20:1673)
    at Object.call (/home/USER/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:13:8361)
    at g.onPromise (/home/USER/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:12:4879)
    at g.onRawMessage (/home/USER/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:12:4267)
    at /home/USER/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:12:3555
    at D.invoke (/home/USER/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:8:145)
    at N.deliver (/home/USER/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:8:2271)
    at h.fire (/home/USER/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:8:1849)
    at process.p (/home/USER/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:6:34973)
    at process.emit (node:events:390:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[2022-06-08 14:40:36.274] [renderer3] [error] ["EPERM: EPERM: operation not permitted, rename 'c:\\Users\\USER\\.vscode\\extensions\\.777b23cc-e37b-4c6a-b899-d85eb9aba606' -> 'c:\\Users\\USER\\.vscode\\extensions\\ms-vscode.cpptools-1.9.8-win32-x64'","    at F.rename (vscode-file://vscode-app/c:/Users/USER/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:213259)","    at async F.extractUserExtension (vscode-file://vscode-app/c:/Users/USER/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:210508)","    at async q.extract (vscode-file://vscode-app/c:/Users/USER/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:217008)","    at async q.doRun (vscode-file://vscode-app/c:/Users/USER/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:217949)"]
[2022-06-08 14:40:36.276] [renderer3] [error] EPERM: operation not permitted, rename 'c:\Users\USER\.vscode\extensions\.777b23cc-e37b-4c6a-b899-d85eb9aba606' -> 'c:\Users\USER\.vscode\extensions\ms-vscode.cpptools-1.9.8-win32-x64': EPERM: EPERM: operation not permitted, rename 'c:\Users\USER\.vscode\extensions\.777b23cc-e37b-4c6a-b899-d85eb9aba606' -> 'c:\Users\USER\.vscode\extensions\ms-vscode.cpptools-1.9.8-win32-x64'
    at F.rename (vscode-file://vscode-app/c:/Users/USER/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:213259)
    at async F.extractUserExtension (vscode-file://vscode-app/c:/Users/USER/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:210508)
    at async q.extract (vscode-file://vscode-app/c:/Users/USER/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:217008)
    at async q.doRun (vscode-file://vscode-app/c:/Users/USER/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:217949)
~~~

### Expected Behaviour

Successful installation.

### Version of Modern Fortran

v3.0.2022042917

### Version of Visual Studio Code

v1.67.2

### Platform and Architecture

Windows 11 Version 21H2

**Comment by gnikit** [comment]
As the message shows this originates from the [`vscode-cpptools`](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools) extension which we use for debugging. About SSH from what I recall the extensions are installed on both the client and the server-side of things, that's the whole point right?! I would clear the extension cache on the remote machine and try and install the [C++ extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools manually. If it succeeds I would then install Modern Fortran, start a Q&A discussion on their GitHub: https://github.com/microsoft/vscode-cpptools/discussions

**Comment by baip** [comment]
Thanks -- that solves it! Did I miss any install instructions..?

**Comment by gnikit** [comment]
> Thanks -- that solves it! Did I miss any install instructions..?

I don't think you missed anything. Vscode is supposed to install all the dependencies of the extensions. Not sure why it didn't work now.

I'll be closing this now, feel free to open a q&a discussion if you have any more questions.
