### ISSUE TITLE
[BUG] install error on VSCode 

### ISSUE THREAD

**Issue by LeeSangHyeup** [fortran-lang/vscode-fortran-support#534]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

on VSCode, when i click "install" button
installation is failed with error logs

### Screenshots

![image](https://user-images.githubusercontent.com/65228113/173477477-eadd2fec-8836-4685-a2c4-b75b5366984d.png)
![image](https://user-images.githubusercontent.com/65228113/173477161-127931b0-a113-400c-945d-b3dab491fd4a.png)
![image](https://user-images.githubusercontent.com/65228113/173477275-c249b714-c9cb-4b01-ac4e-c077bb10aa0a.png)

error messages:
[2022-06-14 10:59:46.735] [renderer1] [error] ["unknown: Server returned 404","    at R (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:26:45595)","    at H.getEngine (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:818)","    at async H.getLastValidExtensionVersionRecursively (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:990)","    at async H.getCompatibleExtensionByEngine (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:45:9075)","    at async H.getCompatibleExtension (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:45:8150)","    at async H.checkAndGetCompatibleVersion (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:216357)","    at async H.installFromGallery (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:214082)"]
[2022-06-14 10:59:46.753] [renderer1] [error] Server returned 404: unknown: Server returned 404
    at R (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:26:45595)
    at H.getEngine (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:818)
    at async H.getLastValidExtensionVersionRecursively (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:990)
    at async H.getCompatibleExtensionByEngine (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:45:9075)
    at async H.getCompatibleExtension (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:45:8150)
    at async H.checkAndGetCompatibleVersion (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:216357)
    at async H.installFromGallery (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:214082)

### Expected Behaviour

succesfully install modern fortran without any errors

### Version of Modern Fortran

v3.1.0

### Version of Visual Studio Code

v1.55.2

### Platform and Architecture

Ubuntu 20.04.2 lts

### Additional Information

GNU Fortran (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

**Comment by gnikit** [comment]
You need to update your VS Code, you are using an extremely outdated version. The extension is supported to VS Code versions v1.63+

**Comment by LeeSangHyeup** [comment]
upgrading VS Code  v1.55.2 to v1.68.0 solved problem
thank you for fast reply

**it was not a bug just version compatibility problem on my system**

**Comment by gnikit** [comment]
No worries, glad I could help!
